apiVersion: v1
kind: ConfigMap
metadata:
  name: apigw-script-configmap
data:
  import.sh: |-
    #!/bin/bash
    set -x;
    while [ $(curl -sw '%{http_code}' "http://api-gateway:5555/rest/apigateway/health" -o /dev/null) -ne 200 ]; do
      sleep 2;
    done    
    curl -LJO  https://raw.githubusercontent.com/kplogesh/InsuranceUsecase/6afe962f7b54e82d02a77195ccbbb38dc487bb1d/assets/insurance/insurance-usecase-type-apigw-mgw/applications/apigateway/sourcecode/insurance-apigw-archive.zip
    curl -X POST 'http://api-gateway:5555/rest/apigateway/archive?overwrite=true&preserveAssetState=true' --header 'Content-Type: application/zip' --header 'Accept: application/json' -u Administrator:manage --data-binary '@'insurance-apigw-archive.zip  
  asset-import.sh: |-
    #!/bin/bash

    set -e
    set -x

    # Base directory containing the APIs
    BASE_DIR="/opt/softwareag/apigwassets/apis"

    # Loop through each subdirectory in the base directory
    for SUBDIR in "$BASE_DIR"/*; do
        if [ -d "$SUBDIR" ]; then
            # Get the subdirectory name
            SUBDIR_NAME=$(basename "$SUBDIR")
            
            # Create the zip file path inside the subdirectory
            ZIP_FILE="${SUBDIR}/${SUBDIR_NAME}.zip"
            
            # Create a zip file for the subdirectory contents
            (cd "$SUBDIR" && zip -r "$ZIP_FILE" ./*)
            
            # Invoke curl with the zipped subdirectory contents and check the status
            CURL_RESPONSE=$(curl --write-out "%{http_code}" --silent --output /dev/null \
            --location 'http://localhost:5555/rest/apigateway/archive?apis=*&overwrite=true&preserveAssetState=true' \
            --header 'Content-Type: multipart/form-data' \
            --header 'Accept: application/json' \
            --header 'Authorization: Basic QWRtaW5pc3RyYXRvcjptYW5hZ2U=' \
            --form "zipFile=@\"$ZIP_FILE\"")
            
            # Check if curl command was successful
            if [ "$CURL_RESPONSE" -ne 200 ]; then
                echo "Upload failed for $ZIP_FILE with status code $CURL_RESPONSE"
                exit 1
            fi
            
            # Remove the zip file after successful upload
            rm "$ZIP_FILE"
        fi
    done